### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by allox** [asaglimbeni/django-datetime-widget#66]
followed the instructions carefully, but nothing seems to work.

**Comment by komackaj** [comment]
Could you setup a minimal case that doesn't work? It should include application's settings.py, models.py with dummy class with DateTimeField named datetime, forms.py + template as described in https://github.com/asaglimbeni/django-datetime-widget#basic-configuration and a view rendering it?

**Comment by asaglimbeni** [comment]
Please be more detailed in your issues report , it is not funny to report "doesn't work at all" when you aren't saying what is not working in you implementation. So we are happy to help to understand if there are any kind of bugs in this widget in order to improve the future release.
Thank you
