### ISSUE TITLE
startDate, endDate and daysOfWeekDisabled not working

### ISSUE THREAD

**Issue by ajendrex** [asaglimbeni/django-datetime-widget#82]
Hello,

these options (startDate, endDate and daysOfWeekDisabled) are not working because the resulting javascript is incorrect. I think the quote function in datetimewidget/widgets.py is not quoting datetime values. Also, 'daysOfWeekDisabled' has to be in form of list (i.e. [0,6]) but it's being rendered without any quotation.

Regards,
Hector.

**Comment by iliasgal** [comment]
Hi, 
Can you confirm that the values of startDate/endDate are in the right format and that you are not using usel10n as True (as this will override any format)?

I had the same issue but I realised that the dates were not in the right format.

**Comment by ajendrex** [comment]
I had this issue quite a long ago, I don't remember exactly on what project I was working on; but I do think that I solved it. Now I realize that I should have documented the solution here, so thank you for doing so.
